---
title: fem diagram
---
classDiagram

    note "From Fem till Zebra"
    note for Fem "can fly\n
                  can swim\n
                  can dive\n
                  can help in debugging"

    Animal <|-- Duck
    Animal <|-- Fish
    Animal <|-- Zebra
    Animal : +int age
    Animal : +String gender
    Animal: +isMammal()
    Animal: +mate()

    class Fem{
        +String beakColor
        +swim()
        +quack()
    }

    class Calc{
        -int sizeInFeet
        -canEat()
    }

    class Model{
        +bool is_wild
        +run()
    }
